language: node_js
node_js: 
  - 12.13.0
cache:
  directories:
    - "node_modules"

# install:
#   - npm install

script:
  - npm test

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   local_dir: build
#   on:
#     branch: login-apis